name: thousandbeanieproject
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49735
title: Thousand Beanie Project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fde9c7'
    - '#110302'
    - '#ba7944'
    - '#f23628'
    - '#bfada2'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
