name: thousandbeanieproject
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49735
title: Thousand Beanie Project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#eb868a'
    - '#000000'
    - '#0036d6'
    - '#01c09e'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
